// RootLayout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  Navbar,
  NavbarBrand,
  NavbarContent,
  NavbarItem,
  NavbarMenuToggle,
  NavbarMenu,
  NavbarMenuItem,
} from "@nextui-org/navbar";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Define the Navbar
const CustomNavbar = () => (
  <Navbar position="static" style={{ backgroundColor: '#000000' }}>
    <NavbarBrand>
      <p className="font-bold text-white" style={{ fontSize: '24px' }}>Tech Blog </p>
    </NavbarBrand>
    <NavbarContent className="hidden sm:flex gap-4" justify="center">
      <NavbarItem>
        <Link href="/aboutUs" className="text-white hover:text-gray-400 transition-colors" style={{ fontSize: '16px' }}>
          About us
        </Link>
      </NavbarItem>
      <NavbarItem>
        <Link href="/blogs" className="text-white hover:text-gray-400 transition-colors" style={{ fontSize: '16px' }}>
          Blogs
        </Link>
      </NavbarItem>
      <NavbarItem>
        <Link href="/addBlogs" className="text-white hover:text-gray-400 transition-colors" style={{ fontSize: '16px' }}>
          Post Blog
        </Link>
      </NavbarItem>
    </NavbarContent>
    <NavbarContent justify="end">
      <NavbarItem className="hidden lg:flex">
        <Link href="/login" className="text-white hover:text-gray-400 transition-colors" style={{ fontSize: '16px' }}>
          Login
        </Link>
      </NavbarItem>
      <NavbarItem>
        <Link href="/signup">
          <button
            className="primary-button"
            style={{
              backgroundColor: '#1a73e8',
              color: 'white',
              padding: '8px 16px',
              borderRadius: '4px',
              fontSize: '16px',
              cursor: 'pointer',
              transition: 'background-color 0.3s ease',
            }}
          
          >
            Sign Up
          </button>
        </Link>
      </NavbarItem>
    </NavbarContent>
  </Navbar>
);


const CustomFooter = () => (
  <footer className="bg-gray-900 text-white py-6">
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div className="flex flex-col md:flex-row justify-between items-center">
        {/* Brand and Description */}
        <div className="flex items-center mb-4 md:mb-0">
          <p className="text-xl font-bold">My App</p>
          <span className="ml-3 text-gray-400">Innovating the Future</span>
        </div>

        {/* Navigation Links */}
        <div className="flex space-x-6">
          <Link href="/about" className="text-gray-400 hover:text-white transition-colors">
            About Us
          </Link>
          <Link href="/services" className="text-gray-400 hover:text-white transition-colors">
            Services
          </Link>
          <Link href="/contact" className="text-gray-400 hover:text-white transition-colors">
            Contact
          </Link>
          <Link href="/privacy" className="text-gray-400 hover:text-white transition-colors">
            Privacy Policy
          </Link>
        </div>

        {/* Social Media Icons */}
        <div className="flex space-x-4 mt-4 md:mt-0">
          <a
            href="https://facebook.com"
            target="_blank"
            rel="noopener noreferrer"
            className="text-gray-400 hover:text-white transition-colors"
            aria-label="Facebook"
          >
            <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
              <path d="M22.675 0H1.325C.594 0 0 .593 0 1.324v21.351C0 23.407.593 24 1.325 24h11.497v-9.294H9.564v-3.622h3.259V8.413c0-3.234 1.974-5.001 4.855-5.001 1.38 0 2.566.103 2.91.149v3.374h-1.995c-1.566 0-1.87.744-1.87 1.837v2.41h3.741l-.488 3.622h-3.253V24h6.377c.73 0 1.325-.593 1.325-1.325V1.325C24 .593 23.406 0 22.675 0z" />
            </svg>
          </a>
          <a
            href="https://twitter.com"
            target="_blank"
            rel="noopener noreferrer"
            className="text-gray-400 hover:text-white transition-colors"
            aria-label="Twitter"
          >
            <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
              <path d="M24 4.557a9.943 9.943 0 01-2.828.775 4.936 4.936 0 002.165-2.724 9.863 9.863 0 01-3.127 1.196 4.924 4.924 0 00-8.384 4.49A13.978 13.978 0 011.671 3.15a4.824 4.824 0 001.523 6.569 4.897 4.897 0 01-2.23-.616v.062a4.93 4.93 0 003.946 4.833 4.903 4.903 0 01-2.224.084 4.93 4.93 0 004.6 3.417 9.867 9.867 0 01-6.102 2.104c-.395 0-.779-.023-1.163-.068a13.945 13.945 0 007.548 2.213c9.053 0 14.004-7.496 14.004-13.986 0-.213-.005-.426-.015-.637A9.935 9.935 0 0024 4.557z" />
            </svg>
          </a>
          <a
            href="https://instagram.com"
            target="_blank"
            rel="noopener noreferrer"
            className="text-gray-400 hover:text-white transition-colors"
            aria-label="Instagram"
          >
            <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
              <path d="M12 2.163c3.204 0 3.584.012 4.85.07 1.366.061 2.633.345 3.608 1.32.975.975 1.259 2.242 1.32 3.608.058 1.266.07 1.646.07 4.84s-.012 3.584-.07 4.85c-.061 1.366-.345 2.633-1.32 3.608-.975.975-2.242 1.259-3.608 1.32-1.266.058-1.646.07-4.85.07s-3.584-.012-4.85-.07c-1.366-.061-2.633-.345-3.608-1.32-.975-.975-1.259-2.242-1.32-3.608C2.175 15.584 2.163 15.204 2.163 12s.012-3.584.07-4.85c.061-1.366.345-2.633 1.32-3.608.975-.975 2.242-1.259 3.608-1.32 1.266-.058 1.646-.07 4.85-.07zM12 0C8.741 0 8.332.014 7.052.072 5.773.129 4.42.404 3.362 1.462.404 4.42.129 5.773.072 7.052.014 8.332 0 8.741 0 12s.014 3.668.072 4.948c.057 1.279.332 2.632 1.29 3.59.959.959 2.311 1.234 3.59 1.29C8.332 23.986 8.741 24 12 24s3.668-.014 4.948-.072c1.279-.057 2.632-.332 3.59-1.29.959-.959 1.234-2.311 1.29-3.59.058-1.28.072-1.689.072-4.948s-.014-3.668-.072-4.948c-.057-1.279-.332-2.632-1.29-3.59-.959-.959-2.311-1.234-3.59-1.29C15.668.014 15.259 0 12 0zm0 5.838c-3.406 0-6.162 2.755-6.162 6.162 0 3.406 2.755 6.162 6.162 6.162 3.406 0 6.162-2.755 6.162-6.162 0-3.406-2.755-6.162-6.162-6.162zm0 10.162c-2.208 0-4-1.793-4-4s1.793-4 4-4 4 1.793 4 4-1.793 4-4 4zm6.406-10.845a1.44 1.44 0 11-.001-2.881 1.44 1.44 0 010 2.881z" />
            </svg>
          </a>
        </div>
      </div>

      {/* Copyright Section */}
      <div className="text-center mt-4">
        <p className="text-gray-400 text-sm">
          &copy; {new Date().getFullYear()} Tech Blog. All rights reserved.
        </p>
      </div>
    </div>
  </footer>
);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CustomNavbar />
        <main>{children}</main>
        <CustomFooter/>
      </body>
    </html>
  );
}
